### ISSUE TITLE
你也做图像检索？

### ISSUE THREAD

**Issue by willard-yuan** [lxiongh/lxiongh.github.io#2]
Hi, lxiongh

从你博客过来的，看了你的那个[Leveraging Semantics with Attribute-associated Auxiliary References for General Image Retrieval](http://lxiongh.github.io/2014/06/02/ImageRetrieval/)，我们老板好像审过这篇文章，O(∩_∩)O哈哈~

**Comment by lxiongh** [comment]
hi，
你好。图像检索是跟一位师兄的合作文章，我主要做图像的解析。^_^

发自我的 iPhone

**Comment by willard-yuan** [comment]
图像解析？是图像理解吧？
